# -*- coding: utf-8 -*-
#
# redaction-technique.org documentation build configuration file, created by
# sphinx-quickstart on Tue Oct 21 18:03:37 2014.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, '.')
# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.todo', 'sphinx.ext.viewcode',
              'sphinxcontrib_awesome', 'sphinx_git']
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'redaction-technique.org'
#copyright = u'CC BY-NC 4.0 - 2011 - 2018, Olivier Carrère'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
#version = '1'
# The full version, including alpha/beta/rc tags.
release = '1.5'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'fr'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

rst_epilog = u"""

.. substitutions
.. |comtech| replace:: communication technique
.. |db| replace:: DocBook
.. |dita| replace:: DITA XML
.. |doc| replace:: documentation technique
.. |flare| replace:: Flare
.. |fm| replace:: FrameMaker
.. |libreoffice| replace:: LibreOffice
.. |ms-word| replace:: MS Word
.. |raspi3| replace:: Raspberry Pi 3
.. |rst| replace:: reStructuredText
.. |site| replace:: blog
.. |techwriter| replace:: rédacteur technique
.. |techwriting| replace:: rédaction technique
.. |cms| replace:: Content Management System
.. |dita-ot| replace:: DITA Open Toolkit
.. |dry| replace:: Don't Repeat Yourself
.. |github| replace:: GitHub
.. |git| replace:: Git
.. |gui| replace:: Graphical User Interface
.. |ide| replace:: Integrated Development Environment
.. |latex| replace:: LaTeX
.. |poc| replace:: Proof of Concept (démonstration de faisabilité)
.. |sphinx| replace:: Python Sphinx
.. |ssh| replace:: SSH
.. |guru| image:: graphics/guru.png
.. |windowsien| image:: graphics/windowsien.png

.. links

sed -i 's,`6 manières`_,[\1](https://www.robertdickau.com/stampfolding.html,g;' *.rst
sed -i 's,`Alfresco`_,[\1](http://www.alfresco.com/fr,g;' *.rst
sed -i 's,`Being a Techie Writer`_,[\1](http://techwhirl.com/techie-writer-series-part-i-being-a-techie-writer/,g;' *.rst
sed -i 's,`CSS`_,[\1](https://github.com/olivier-carrere/redaction-technique.org/tree/master/_static,g;' *.rst
sed -i 's,`Componize`_,[\1](http://www.componize.com,g;' *.rst
sed -i 's,`DITA Open Toolkit 1.5.4`_,[\1](http://sourceforge.net/projects/dita-ot/files/DITA-OT Stable Release/DITA Open Toolkit 1.5.4/DITA-OT1.5.4_full_easy_install_bin.zip/download,g;' *.rst
sed -i 's,`DITA XML`_,[\1](https://github.com/olivier-carrere/redaction-technique.org/tree/DITA_XML,g;' *.rst
sed -i 's,`DITA integration for Drupal`_,[\1](http://drupal.org/project/dita,g;' *.rst
sed -i 's,`DocBook`_,[\1](https://github.com/olivier-carrere/redaction-technique.org/tree/DocBook,g;' *.rst
sed -i 's,`DocZone`_,[\1](http://www.doczone.com,g;' *.rst
sed -i 's,`Flask`_,[\1](http://flask.pocoo.org/,g;' *.rst
sed -i 's,`FrameMaker`_,[\1](http://en.wikipedia.org/wiki/Adobe_FrameMaker,g;' *.rst
sed -i 's,`Git for windows`_,[\1](https://github.com/git-for-windows/git/releases/download/v2.18.0.windows.1/Git-2.18.0-64-bit.exe,g;' *.rst
sed -i 's,`Git`_,[\1](http://www.git-scm.com,g;' *.rst
sed -i 's,`GitHub Desktop`_,[\1](https://desktop.github.com/,g;' *.rst
sed -i 's,`GitHub`_,[\1](https://github.com/,g;' *.rst
sed -i 's,`Gummi`_,[\1](https://github.com/alexandervdm/gummi,g;' *.rst
sed -i 's,`JPEG`_,[\1](http://fr.wikipedia.org/wiki/Jpeg,g;' *.rst
sed -i 's,`Java`_,[\1](http://java.com/fr/download/manual.jsp?locale=fr,g;' *.rst
sed -i 's,`Jinja`_,[\1](http://jinja.pocoo.org/,g;' *.rst
sed -i 's,`Jourdainisez votre tirade`_,[\1](https://oliviercarrere.pythonanywhere.com/,g;' *.rst
sed -i 's,`LFTP`_,[\1](https://lftp.yar.ru/,g;' *.rst
sed -i 's,`LaTeX`_,[\1](https://www.latex-project.org/,g;' *.rst
sed -i 's,`LinkedIn`_,[\1](http://fr.linkedin.com/in/carrereolivier,g;' *.rst
sed -i 's,`Linux sur Android`_,[\1](https://korben.info/comment-installer-linux-sur-android.html,g;' *.rst
sed -i 's,`Makefile`_,[\1](https://github.com/olivier-carrere/redaction-technique.org/commits/master/Makefile,g;' *.rst
sed -i 's,`NOOBS`_,[\1](https://www.raspberrypi.org/downloads/noobs/,g;' *.rst
sed -i 's,`NuFirewall`_,[\1](http://linuxfr.org/news/nufirewall-le-pare-feu-libre-sans-prise-de-t%C3%AAte,g;' *.rst
sed -i 's,`Obambu`_,[\1](https://obambu.com/fr/hebergement/,g;' *.rst
sed -i 's,`OpenDocument`_,[\1](http://fr.wikipedia.org/wiki/OpenDocument,g;' *.rst
sed -i 's,`Photo Kevin Harber:  https://www.flickr.com/photos/kevharb/5391858379,g;' *.rst
sed -i 's,`Piwigo`_,[\1](http://piwigo.org/,g;' *.rst
sed -i 's,`Predictive`_,[\1](http://www.dr-qubit.org/emacs.php#predictive-download,g;' *.rst
sed -i 's,`RAW`_,[\1](http://fr.wikipedia.org/wiki/RAW_(format_d%27image),g;' *.rst
sed -i 's,`Read the Docs`_,[\1](https://readthedocs.org/projects/redaction-techniqueorg,g;' *.rst
sed -i 's,`SimpleScreenRecorder`_,[\1](http://www.maartenbaert.be/simplescreenrecorder/,g;' *.rst
sed -i 's,`SyncToy`_,[\1](http://www.microsoft.com/en-us/download/details.aspx?id=15155,g;' *.rst
sed -i 's,`TIFF`_,[\1](http://fr.wikipedia.org/wiki/Tagged_Image_File_Format,g;' *.rst
sed -i 's,`Trac`_,[\1](http://trac.edgewall.org,g;' *.rst
sed -i 's,`Unison`_,[\1](http://www.cis.upenn.edu/~bcpierce/unison,g;' *.rst
sed -i 's,`XML::Twig`_,[\1](http://www.xmltwig.org/xmltwig/,g;' *.rst
sed -i 's,`XPATH`_,[\1](http://fr.wikipedia.org/wiki/XPath,g;' *.rst
sed -i 's,`XSD`_,[\1](http://fr.wikipedia.org/wiki/XML_Schema,g;' *.rst
sed -i 's,`XSL-FO`_,[\1](http://fr.wikipedia.org/wiki/XSL-FO,g;' *.rst
sed -i 's,`classe de documents LaTeX leaflet`_,[\1](https://ctan.org/pkg/leaflet,g;' *.rst
sed -i 's,`conref`_,[\1](http://docs.oasis-open.org/dita/v1.1/OS/archspec/conref.html,g;' *.rst
sed -i 's,`ditaval`_,[\1](http://docs.oasis-open.org/dita/v1.2/os/spec/common/about-ditaval.html,g;' *.rst
sed -i 's,`expressions rationnelles`_,[\1](http://fr.wikipedia.org/wiki/Expression_rationnelle,g;' *.rst
sed -i 's,`fdupes`_,[\1](https://github.com/adrianlopezroche/fdupes,g;' *.rst
sed -i 's,`file`_,[\1](https://www.computerhope.com/unix/ufile.htm,g;' *.rst
sed -i 's,`l'archive des fichiers schemas.xml`_,[\1](http://www.redaction-technique.org/media/schemas.redaction-technique.org.tar.gz,g;' *.rst
sed -i 's,`l'archive des schémas RelaxNG pour DITA XML`_,[\1](http://www.redaction-technique.org/media/rnc.tar.gz,g;' *.rst
sed -i 's,`minimalisme`_,[\1](https://www.utwente.nl/en/bms/ist/minimalism/,g;' *.rst
sed -i 's,`minimaliste`_,[\1](https://www.instructionaldesign.org/theories/minimalism/,g;' *.rst
sed -i 's,`modèle LaTeX du dépliant`_,[\1](https://www.overleaf.com/latex/templates/leaflet/ysdkbbhctfpc,g;' *.rst
sed -i 's,`nombreux avantages de LaTeX`_,[\1](https://www.plpeeters.com/blog/fr/post/110-introduction-a-latex#comparaison-word-et-consorts-vs-latex,g;' *.rst
sed -i 's,`perspective de l'utilisateur`_,[\1](https://www.utwente.nl/en/bms/ist/minimalism/principle2/,g;' *.rst
sed -i 's,`piwigo.com`_,[\1](https://piwigo.com/plan,g;' *.rst
sed -i 's,`reStructuredText`_,[\1](https://github.com/olivier-carrere/redaction-technique.org/tree/master,g;' *.rst
sed -i 's,`reltable`_,[\1](http://docs.oasis-open.org/dita/v1.0/langspec/reltable.html,g;' *.rst
sed -i 's,`rsync`_,[\1](http://rsync.samba.org,g;' *.rst
sed -i 's,`script de génération multilingue DITA XML`_,[\1](http://www.redaction-technique.org/media/dita2target.sh,g;' *.rst
sed -i 's,`scripts Bash`_,[\1](https://github.com/olivier-carrere/redaction-technique.org/tree/master/scripts,g;' *.rst
sed -i 's,`spécialisation`_,[\1](http://en.wikipedia.org/wiki/Darwin_Information_Typing_Architecture#Specialization,g;' *.rst
sed -i 's,`thèse de doctorat`_,[\1](https://texfaq.org/FAQ-hyphen,g;' *.rst
sed -i 's,`topics`_,[\1](http://docs.oasis-open.org/dita/v1.0/archspec/topicover.html,g;' *.rst
sed -i 's,`un point fort du produit`_,[\1](http://www.linformaticien.com/tests/id/20068/categoryid/48/edenwall-nufirewall-le-pare-feu-nouvelle-generation.aspx,g;' *.rst
sed -i 's,`xinclude`_,[\1](http://en.wikipedia.org/wiki/XInclude,g;' *.rst
sed -i 's,`xml_split`_,[\1](http://search.cpan.org/dist/XML-Twig/tools/xml_split/xml_split,g;' *.rst

,g;' *.rst
# -- Options for HTML output ---------------------------------------------------,g;' *.rst
,g;' *.rst
# The theme to use for HTML and HTML Help pages.  See the documentation for,g;' *.rst
# a list of builtin themes.,g;' *.rst
import sphinx_rtd_theme,g;' *.rst
,g;' *.rst
html_theme = "sphinx_rtd_theme",g;' *.rst
,g;' *.rst
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()],g;' *.rst
,g;' *.rst
# Theme options are theme-specific and customize the look and feel of a theme,g;' *.rst
# further.  For a list of options available for each theme, see the,g;' *.rst
# documentation.,g;' *.rst
,g;' *.rst
# Add any paths that contain custom themes here, relative to this directory.,g;' *.rst
#html_theme_path = [],g;' *.rst
,g;' *.rst
# The name for this set of Sphinx documents.  If None, it defaults to,g;' *.rst
# "<project> v<release> documentation".,g;' *.rst
html_title = u' La documentation est une valeur ajoutée du logiciel.',g;' *.rst
,g;' *.rst
# A shorter title for the navigation bar.  Default is the same as html_title.,g;' *.rst
#html_short_title = None,g;' *.rst
,g;' *.rst
# The name of an image file (relative to this directory) to place at the top,g;' *.rst
# of the sidebar.,g;' *.rst
html_logo = "graphics/redaction-technique.png",g;' *.rst
,g;' *.rst
# The name of an image file (within the static path) to use as favicon of the,g;' *.rst
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32,g;' *.rst
# pixels large.,g;' *.rst
html_favicon = "graphics/favicon.png",g;' *.rst
,g;' *.rst
# Add any paths that contain custom static files (such as style sheets) here,,g;' *.rst
# relative to this directory. They are copied after the builtin static files,,g;' *.rst
# so a file named "default.css" will overwrite the builtin "default.css".,g;' *.rst
html_static_path = ['_static'],g;' *.rst
,g;' *.rst
# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,,g;' *.rst
# using the given strftime format.,g;' *.rst
html_last_updated_fmt = '%Y',g;' *.rst
,g;' *.rst
# If true, SmartyPants will be used to convert quotes and dashes to,g;' *.rst
# typographically correct entities.,g;' *.rst
#html_use_smartypants = True,g;' *.rst
,g;' *.rst
# Custom sidebar templates, maps document names to template names.,g;' *.rst
#html_sidebars = {},g;' *.rst
,g;' *.rst
# Additional templates that should be rendered to pages, maps page names to,g;' *.rst
# template names.,g;' *.rst
#html_additional_pages = {},g;' *.rst
,g;' *.rst
# If false, no module index is generated.,g;' *.rst
#html_domain_indices = True,g;' *.rst
,g;' *.rst
# If false, no index is generated.,g;' *.rst
html_use_index = False,g;' *.rst
,g;' *.rst
# If true, the index is split into individual pages for each letter.,g;' *.rst
#html_split_index = False,g;' *.rst
,g;' *.rst
# If true, links to the reST sources are added to the pages.,g;' *.rst
html_show_sourcelink = True,g;' *.rst
,g;' *.rst
# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.,g;' *.rst
html_show_sphinx = False,g;' *.rst
,g;' *.rst
# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.,g;' *.rst
#html_show_copyright = True,g;' *.rst
,g;' *.rst
# If true, an OpenSearch description file will be output, and all pages will,g;' *.rst
# contain a <link> tag referring to it.  The value of this option must be the,g;' *.rst
# base URL from which the finished HTML is served.,g;' *.rst
#html_use_opensearch = '',g;' *.rst
,g;' *.rst
# This is the file name suffix for HTML files (e.g. ".xhtml").,g;' *.rst
#html_file_suffix = None,g;' *.rst
,g;' *.rst
# Output file base name for HTML help builder.,g;' *.rst
htmlhelp_basename = 'redaction-techniqueorgdoc',g;' *.rst
,g;' *.rst
,g;' *.rst
# -- Options for LaTeX output --------------------------------------------------,g;' *.rst
,g;' *.rst
latex_elements = {,g;' *.rst
# The paper size ('letterpaper' or 'a4paper').,g;' *.rst
    'papersize': 'a4paper',,g;' *.rst
,g;' *.rst
# The font size ('10pt', '11pt' or '12pt').,g;' *.rst
#'pointsize': '10pt',,g;' *.rst
,g;' *.rst
# Additional stuff for the LaTeX preamble.,g;' *.rst
#'preamble': '',,g;' *.rst
,g;' *.rst
    'babel': '\\usepackage[francais]{babel}',,g;' *.rst
    'preamble': '\\usepackage{redaction-technique}',,g;' *.rst
    'classoptions': ',openany',,g;' *.rst
},g;' *.rst
,g;' *.rst
latex_additional_files = [,g;' *.rst
    '_themes/redaction-technique.sty',,g;' *.rst
    '_themes/wallpaper.sty',,g;' *.rst
 ],g;' *.rst
,g;' *.rst
# Grouping the document tree into LaTeX files. List of tuples,g;' *.rst
# (source start file, target name, title, author, documentclass [howto/manual]).,g;' *.rst
latex_documents = [,g;' *.rst
  ('index', 'redaction-techniqueorg.tex', u'Processus de rédaction technique',,g;' *.rst
   u'Olivier Carrère', 'manual', 'toctree_only'),,g;' *.rst
],g;' *.rst
,g;' *.rst
# The name of an image file (relative to this directory) to place at the top of,g;' *.rst
# the title page.,g;' *.rst
latex_logo = "graphics/redaction-technique.pdf",g;' *.rst
,g;' *.rst
# For "manual" documents, if this is true, then toplevel headings are parts,,g;' *.rst
# not chapters.,g;' *.rst
#latex_use_parts = False,g;' *.rst
,g;' *.rst
# If true, show page references after internal links.,g;' *.rst
latex_show_pagerefs = True,g;' *.rst
,g;' *.rst
# If true, show URL addresses after external links.,g;' *.rst
latex_show_urls = 'footnote',g;' *.rst
,g;' *.rst
# Documents to append as an appendix to all manuals.,g;' *.rst
#latex_appendices = [],g;' *.rst
,g;' *.rst
# If false, no module index is generated.,g;' *.rst
#latex_domain_indices = True,g;' *.rst
,g;' *.rst
,g;' *.rst
# -- Options for manual page output --------------------------------------------,g;' *.rst
,g;' *.rst
# One entry per manual page. List of tuples,g;' *.rst
# (source start file, name, description, authors, manual section).,g;' *.rst
man_pages = [,g;' *.rst
    ('index', 'redaction-techniqueorg', u'redaction-technique.org Documentation',,g;' *.rst
     [u'Olivier Carrère'], 1),g;' *.rst
],g;' *.rst
,g;' *.rst
# If true, show URL addresses after external links.,g;' *.rst
#man_show_urls = False,g;' *.rst
,g;' *.rst
# -- Options for Epub output ---------------------------------------------------,g;' *.rst
,g;' *.rst
# Bibliographic Dublin Core info.,g;' *.rst
epub_title = u'redaction-technique.org',g;' *.rst
epub_author = u'Olivier Carrère',g;' *.rst
epub_publisher = u'Olivier Carrère',g;' *.rst
epub_copyright = u'2015, Olivier Carrère',g;' *.rst
,g;' *.rst
# The language of the text. It defaults to the language option,g;' *.rst
# or en if the language is not set.,g;' *.rst
#epub_language = '',g;' *.rst
,g;' *.rst
# The scheme of the identifier. Typical schemes are ISBN or URL.,g;' *.rst
#epub_scheme = '',g;' *.rst
,g;' *.rst
# The unique identifier of the text. This can be a ISBN number,g;' *.rst
# or the project homepage.,g;' *.rst
#epub_identifier = '',g;' *.rst
,g;' *.rst
# A unique identification for the text.,g;' *.rst
#epub_uid = '',g;' *.rst
,g;' *.rst
# A tuple containing the cover image and cover page html template filenames.,g;' *.rst
#epub_cover = (),g;' *.rst
,g;' *.rst
# HTML files that should be inserted before the pages created by sphinx.,g;' *.rst
# The format is a list of tuples containing the path and title.,g;' *.rst
#epub_pre_files = [],g;' *.rst
,g;' *.rst
# HTML files shat should be inserted after the pages created by sphinx.,g;' *.rst
# The format is a list of tuples containing the path and title.,g;' *.rst
#epub_post_files = [],g;' *.rst
,g;' *.rst
# A list of files that should not be packed into the epub file.,g;' *.rst
#epub_exclude_files = [],g;' *.rst
,g;' *.rst
# The depth of the table of contents in toc.ncx.,g;' *.rst
#epub_tocdepth = 3,g;' *.rst
,g;' *.rst
# Allow duplicate toc entries.,g;' *.rst
#epub_tocdup = True,g;' *.rst
