.. Copyright 2011-2015 Olivier Carrère
.. Cette œuvre est mise à disposition selon les termes de la licence Creative
.. Commons Attribution - Pas d'utilisation commerciale - Partage dans les mêmes
.. conditions 4.0 international.

.. code review: no code

À propos de ce |site|
---------------------

Ce |site| est conçu et réalisé par un |techwriter| spécialisé dans
l'informatique.

Il a parlé, parle ou parlera un peu, beaucoup ou pas du tout des formats, des
outils et des tâches suivants :

+-----------------------------------+-------------------------+----------------+
|Tâche                              ||rst|                    ||dita|          |
+===================================+=========================+================+
|Modification                       |`scripts Bash`_                           |
|                                   +------------------------------------------+
|                                   |awk                                       |
|                                   +------------------------------------------+
|                                   |sed                                       |
|                                   +------------------------------------------+
|                                   |expressions rationnelles (ou *expressions |
|                                   |régulières*)                              |
+-----------------------------------+------------------------------------------+
|Gestion de versions                |Git                                       |
+-----------------------------------+-------------------------+----------------+
|Compilation                        |`Makefile`_              |Ant             |
|                                   |                         +----------------+
|                                   |                         |XSLT            |
+---------------------+-------------+-------------------------+----------------+
|Mise en page         |HTML         |`CSS`_                                    |
|                     +-------------+-------------------------+----------------+
|                     |PDF          |LaTeX                    |XSL-FO          |
+---------------------+-------------+-------------------------+----------------+

Puisqu'il traite des processus et des formats de rédaction technique, son
contenu est cependant moins pertinent que son historique et que ses branches
Git.

.. text review: yes
