.. Copyright 2011-2014 Olivier Carrère
.. Cette œuvre est mise à disposition selon les termes de la licence Creative
.. Commons Attribution - Pas d'utilisation commerciale - Partage dans les mêmes
.. conditions 4.0 international.

.. code review: no code

Formats cibles
--------------

Vous pouvez compiler ce |site| avec *Python Sphinx* aux formats :

- PDF,
- HTML,
- EPUB.

Vous pouvez également obtenir une version compilée sur `Read the Docs`_.

.. text review: yes
