.. Copyright 2011-2014 Olivier Carrère
.. Cette œuvre est mise à disposition selon les termes de la licence Creative
.. Commons Attribution - Pas d'utilisation commerciale - Partage dans les mêmes
.. conditions 4.0 international.

.. code review: no code

Formats cibles
--------------

Vous pouvez compiler ce |site| avec *Python Sphinx* aux formats :

- PDF,
- `EPUB`_,
- HTML.

.. raw:: html

   <iframe id="pdf" style="border:1px solid #6a6a6a" title="Version PDF"
   src="download/redaction-techniqueorg.pdf" frameborder="1" scrolling="auto"
   width="100%" height="1050"></iframe>

*Version* |release| *de ce site au format PDF*

Ces différentes versions sont générées à partir des mêmes sources
exactement. Elles présentent cependant de légères variations, mises en œuvre par
un mécanisme de texte conditionnel. Par exemple, le terme suivant varie selon le
format cible :

+------------------------------+------------------------------+
|Format cible                  |Terme                         |
+==============================+==============================+
|PDF                           |document                      |
+------------------------------+------------------------------+
|EPUB                          |livre électronique            |
+------------------------------+------------------------------+
|HTML                          |site                          |
+------------------------------+------------------------------+

.. _PDF: download/redaction-techniqueorg.pdf
.. _EPUB: download/redaction-techniqueorg.epub

.. seealso::

   - :ref:`creer-des-documents-differents-a-partir-des-memes-sources-dita-xml-texte-conditionnel`

.. text review: yes
