.. Copyright 2011-2015 Olivier Carrère
.. Cette œuvre est mise à disposition selon les termes de la licence Creative
.. Commons Attribution - Pas d'utilisation commerciale - Partage dans les mêmes
.. conditions 4.0 international.

.. code review: no code

Les sources de ce |site| sont gérées sous Git
---------------------------------------------

Ce |site| a été initialement développé sous WordPress. L'impossibilité
d'effectuer sous ce |cms| des modifications transverses ou d'avoir un suivi
précis du cycle de vie du contenu a entraîné une migration vers le format de
balisage léger |rst|.

.. figure:: graphics/documentation-life-cycle-framework.png

Toutes les versions de ce |site| sont gérées sous le logiciel de gestion de
versions décentralisé `Git`_. Les modifications de contenu, de structure ou de
mise en page peuvent désormais être :

- regroupées par lots cohérents,
- liées à un ticket de logiciel de suivi de problèmes tel que *Bugzilla* ou
  *Trac*,
- validées par des pairs,
- partagées entre différentes versions du projet de documentation,
- annulées en une seule opération, etc.

.. text review: yes
