.. Copyright 2011-2014 Olivier Carrère
.. Cette œuvre est mise à disposition selon les termes de la licence Creative
.. Commons Attribution - Pas d'utilisation commerciale - Partage dans les mêmes
.. conditions 4.0 international.

.. code review: no code

Sortir l'information de ses silos
=================================

Qu'est-ce qu'un fichier **Word** ou |fm| ? Un silo d'information cloisonné. Les
données qu'il contient ne peuvent pratiquement pas être partagées ni gérées
individuellement.

Les deux freins à l'adoption d'un modèle plus performant, modulaire et ouvert,
sont le coût de migration et la formation des rédacteurs techniques. Cependant,
l'effort initial est rapidement et largement compensé par les gains de
productivité, de souplesse, de qualité, de suivi et de réactivité.

.. text review: yes
